---
ID: "c9f0ae99-4b6a-4848-87ca-d5e41c331bcf"
Parent: "74d94262-c696-4b9f-aaec-2d342f45bf26"
Template: "74d94262-c696-4b9f-aaec-2d342f45bf26"
Path: /sitecore/templates/Project/Common/Page Types/FAQ/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{1D517D38-25AF-4702-9340-807ADCBFF2DE}">
        <r
          id="{4CFC6277-BD95-45D8-8A33-C10AB9858F0B}"
          ph="main"
          uid="{542458CC-5FC1-4067-982C-E75CD325AD11}" />
        <r
          id="{3ED979E5-AB17-40EE-AA78-838907D5F1FB}"
          ph="header"
          uid="{4E98B411-4AA2-443B-BCF1-2C872FEB3E11}" />
        <r
          id="{21B86F93-F4B1-467D-A676-FE32C4144CEC}"
          ph="PhNavigationBar"
          uid="{5E7B4370-7937-4DCD-B559-CD200D9D1BE7}" />
        <r
          id="{44954101-6B69-43AA-85AF-308A5167FF93}"
          ph="PhRightNavigationBar"
          uid="{C787998E-2067-4328-983C-E0CCF5006B36}" />
        <r
          id="{D27897F7-3D6A-4788-A2E1-3D25DC4582B4}"
          ph="footer"
          uid="{6F700967-C06B-4010-B020-F734DB32586C}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201105T122212Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
