---
ID: "0a3de7e7-8aea-43b8-bd1f-6e229409ffe6"
Parent: "0d7b46d8-df86-4ae9-bb19-0a8e9909af23"
Template: "0d7b46d8-df86-4ae9-bb19-0a8e9909af23"
Path: /sitecore/templates/Feature/Scroll Navigation/Scroll Nav/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201222T075128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d3bc94d9-5a7b-4b00-8a90-9017f186294a"
      Hint: Title
      Value: $name
