---
ID: "998d6303-094d-4581-a27d-360c41290aaf"
Parent: "c18d3794-d126-4548-bfc8-89358de6e9c1"
Template: "c18d3794-d126-4548-bfc8-89358de6e9c1"
Path: /sitecore/templates/Project/Common/Content Types/Media/Carousel/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201011T181147Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
