---
ID: "692fb15a-8723-4d6b-b837-c489fe5dcb23"
Parent: "f5fa406e-51c4-4a15-b0bf-5ba2595fb7aa"
Template: "f5fa406e-51c4-4a15-b0bf-5ba2595fb7aa"
Path: /sitecore/templates/Feature/Social/Social/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201102T062719Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
