---
ID: "8aa95df5-ab50-45aa-861d-a5c596636b94"
Parent: "75c60227-4dd3-40e1-91a2-80c7e734f92d"
Template: "75c60227-4dd3-40e1-91a2-80c7e734f92d"
Path: /sitecore/templates/Feature/Media/Banner/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201023T070333Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
