---
ID: "6f090b16-d4a5-452b-bd6b-de3805a66ef6"
Parent: "33b41029-6ad4-4f5c-af68-97f343b8ede0"
Template: "33b41029-6ad4-4f5c-af68-97f343b8ede0"
Path: /sitecore/templates/Feature/Footer/Footer Links/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201102T083817Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
