---
ID: "17fcec16-9c56-4793-99f5-bd69efc01a57"
Parent: "86fa8d73-b262-47ba-9e5b-44f30cd48457"
Template: "4c82b6dd-fe7c-4144-bcb3-f21b4080568f"
Path: /sitecore/content/FordIndia/Site Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201011T163203Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
