---
ID: "b5f2cbdc-bc7e-4037-9a7d-0ae24cd5c999"
Parent: "88f46b65-1b45-4339-b452-ead039ad2eff"
Template: "88f46b65-1b45-4339-b452-ead039ad2eff"
Path: /sitecore/templates/Project/FordIndia/Page Types/Content Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{1D517D38-25AF-4702-9340-807ADCBFF2DE}">
        <r
          id="{4CFC6277-BD95-45D8-8A33-C10AB9858F0B}"
          ph="main"
          uid="{F854F0A7-DE1D-4B0D-BBE2-CE78BB84A392}" />
        <r
          id="{3ED979E5-AB17-40EE-AA78-838907D5F1FB}"
          ph="header"
          uid="{E70A6117-0636-4FFD-B04E-95946622D568}" />
        <r
          id="{21B86F93-F4B1-467D-A676-FE32C4144CEC}"
          ph="PhNavigationBar"
          uid="{1DD943D0-35B1-4608-8926-4BC92C541CFA}" />
        <r
          id="{44954101-6B69-43AA-85AF-308A5167FF93}"
          ph="PhRightNavigationBar"
          uid="{2758CD6D-A2C0-460C-BE25-FB7B4236A7B0}" />
        <r
          id="{E44676F7-378F-4FCE-9320-EA5B2AAD8796}"
          ph="main"
          uid="{63B51DD1-5F64-4215-9F18-0541DE78E315}" />
        <r
          id="{AA9CE665-07DA-4678-8F4D-06371C11088F}"
          ph="main"
          uid="{B26360F6-4DC0-4A94-8D7E-FDA93510648F}" />
        <r
          id="{D27897F7-3D6A-4788-A2E1-3D25DC4582B4}"
          ph="footer"
          uid="{435361DF-9D01-45A1-B292-3A0A105CFA3B}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201030T050301Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
