---
ID: "643836a7-633e-4ec6-8886-5e6de34aaf5e"
Parent: "bdc9fe50-3ade-4203-8179-3df6fd6c4db2"
Template: "bdc9fe50-3ade-4203-8179-3df6fd6c4db2"
Path: /sitecore/templates/Project/FordIndia/Page Types/SubCategory Landing/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{1D517D38-25AF-4702-9340-807ADCBFF2DE}">
        <r
          id="{3ED979E5-AB17-40EE-AA78-838907D5F1FB}"
          ph="header"
          uid="{B641BB02-ECC7-458E-B31D-E9A2B9BE789A}" />
        <r
          id="{21B86F93-F4B1-467D-A676-FE32C4144CEC}"
          ph="PhNavigationBar"
          uid="{BAA85F72-6809-48CD-B81C-28D01923E150}" />
        <r
          id="{44954101-6B69-43AA-85AF-308A5167FF93}"
          ph="PhRightNavigationBar"
          uid="{4863D906-B316-476C-8682-4715F4C4C350}" />
        <r
          ds="{15FF62FD-AADE-4563-BC42-51CCE3D761F9}"
          id="{9A71EDB7-E1D6-4CDD-896B-0F64E8753978}"
          par=""
          ph="main"
          uid="{781D7837-45D1-4624-9A74-72A1C78547F2}" />
        <r
          id="{E77B703F-38ED-46C0-A8A2-3D619ECC6D68}"
          ph="main"
          uid="{59B1A707-A972-45DD-AC68-42BD3440D4FF}" />
        <r
          id="{D27897F7-3D6A-4788-A2E1-3D25DC4582B4}"
          ph="footer"
          uid="{955AD45C-FEB1-4F4D-B727-06D20964B7F8}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201023T073432Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
