---
ID: "643836a7-633e-4ec6-8886-5e6de34aaf5e"
Parent: "bdc9fe50-3ade-4203-8179-3df6fd6c4db2"
Template: "bdc9fe50-3ade-4203-8179-3df6fd6c4db2"
Path: /sitecore/templates/Project/Common/Page Types/SubCategory Landing/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201023T073432Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
