---
ID: "7b6bd5a4-bd6e-4784-abb2-559f5e3c58c7"
Parent: "b2418257-ca45-4c40-bc90-bf2edbb16f01"
Template: "b2418257-ca45-4c40-bc90-bf2edbb16f01"
Path: "/sitecore/templates/Feature/3-4 Feature/HeaderDetails/__Standard Values"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201217T081413Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
